name: native_image
description: Flutter plugin for handling images on iOS and Android
version: 1.0.0
homepage: https://teddichiiwa.com
repository: https://github.com/teddichiiwa/native_image/tree/main/native_image
issue_tracker: https://github.com/teddichiiwa/native_image/issues
documentation: https://github.com/teddichiiwa/native_image.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

  native_image_platform_interface: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # linter
  vm_lint:
    git:
      url: https://github.com/teddichiiwa/vm_lint.git

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: com.teddichiiwa.native_image
        pluginClass: NativeImagePlugin
      ios:
        pluginClass: NativeImagePlugin
